title: Adam Qureshi
description: Notes on building, selling, and staying small on purpose.
author: Adam Qureshi
theme: minima

url: https://adamqureshi.com
timezone: America/New_York
permalink: /:categories/:title/
future: false

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

header_pages:
  - about.md

url: https://adamqureshi.com
timezone: America/New_York
permalink: /:categories/:title/
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
